(function(){
'use strict';
const C=ExamCore,E=C.escape,c=COURSE,year=c.years[0];
C.validateCourse(c);
const key='demo-template-2026-preferences';
let memory={},storageAvailable=true;
function get(k){if(Object.hasOwn(memory,k))return memory[k];try{return localStorage.getItem(k);}catch{storageAvailable=false;return null;}}
function set(k,v){memory[k]=v;try{localStorage.setItem(k,v);}catch{storageAvailable=false;}}
let pref={};try{const parsed=JSON.parse(get(key)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))pref=parsed;}catch{}
const query=new URLSearchParams(location.search);
let mode=['learn','training','mock'].includes(query.get('mode')||pref.mode)?query.get('mode')||pref.mode:'learn';
let stack=(query.get('stack')||pref.stack)==='postgresql'?'postgresql':'mysql';
let module=year.modules.find(m=>m.id===(query.get('module')||pref.module))||year.modules[0];
let lessonView=query.get('view')==='example'?'example':'steps';
let section=['work','examples','programs','criteria','teacher'].includes(query.get('section'))?query.get('section'):'work';
if(section==='work'&&lessonView==='example')section='examples';
if(section==='examples'){lessonView='example';mode='learn';}else if(section==='work')lessonView='steps';
let routeStage=ExamLearningRoute.stages.some(s=>s.id===query.get('stage'))?query.get('stage'):(query.has('module')?module.id:(pref.stage||'documents'));
if(!ExamLearningRoute.stages.some(s=>s.id===routeStage))routeStage='documents';
if(section==='work'&&mode==='learn')module=year.modules.find(m=>m.id===(routeStage==='documents'?'M1':routeStage));
let returnToTraining=false;
let dark=typeof pref.dark==='boolean'?pref.dark:matchMedia('(prefers-color-scheme: dark)').matches;
function save(){set(key,JSON.stringify({mode,stack,module:module.id,dark,stage:routeStage}));const u=new URL(location.href);u.searchParams.set('stage',routeStage);u.searchParams.set('section',section);u.searchParams.set('mode',mode);u.searchParams.set('module',module.id);u.searchParams.set('stack',stack);u.searchParams.set('view',lessonView);history.replaceState(null,'',u);}
function clearStepHash(){const u=new URL(location.href);u.hash='';history.replaceState(null,'',u);}
function change(action){if((mode==='mock'&&ExamPractice.isRunning())&&!confirm('Таймер продолжит идти в фоне. Перейти к другому разделу?'))return false;action();save();render();return true;}
function download(files,name){const u=URL.createObjectURL(new Blob([C.zip(files)],{type:'application/zip'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function map(){return `<section class="exam-map"><div class="map-heading"><div><span class="section-code">КОД 09.02.07-5-2026 · БАЗОВЫЙ УРОВЕНЬ</span><h2>Карта демонстрационного экзамена</h2><p>Пять модулей: от модели данных до документации</p></div><div class="map-total"><strong>50</strong><span>максимум баллов</span></div><div class="map-total"><strong>2:30</strong><span>часа на экзамен</span></div></div></section>`;}

const moduleResults={M1:['Таблицы и поля по исходным Excel и JSON','Ключи и связи; общие данные не дублируются','Читаемая ER-диаграмма в PDF'],M2:['Таблицы по своей ER-диаграмме','Правильные типы полей, ключи и запрет неверных ссылок','Импорт исходных заказчиков без потери значений'],M3:['Стоимость всех материалов с учётом количества продукции','Проверенные нормы расхода и цены материалов','Сохранённый SQL и проверенный результат'],M4:['Формы и действия по заданию','Авторизация, пазл, роли и блокировка','Работа приложения с созданной базой'],M5:['Назначение и условия запуска своей системы','Описание реализованных методов и параметров','Инструкции, снимки своих окон и результаты проверок']};
function assessment(){return `<section class="module-assessment" aria-label="Результат модуля"><h3>Что должно получиться</h3><ul>${moduleResults[module.id].map(t=>'<li>'+E(t)+'</li>').join('')}</ul><a href="?section=criteria">Как оценивают экзамен →</a></section>`;}
function criteria(){return `<article class="article criteria-page"><span class="section-code">ОЦЕНИВАНИЕ · ВЕСЬ ЭКЗАМЕН</span><h1>Официальные критерии</h1><p>Максимум — <strong>50 баллов</strong>. Это семь критериев для всей работы. Их баллы нельзя складывать как оценки за модули.</p><div class="scroll-table"><table><thead><tr><th scope="col">Критерий</th><th scope="col">Максимум</th></tr></thead><tbody>${year.assessment.criteria.map(r=>`<tr><td>${E(r.title)}</td><td><strong>${r.points}</strong></td></tr>`).join('')}</tbody><tfoot><tr><th scope="row">Всего</th><td>50</td></tr></tfoot></table></div><p>В разборе каждого модуля есть список результата для самопроверки. Галочки и таймер на сайте не выставляют оценку.</p><a href="sources/2026.pdf" target="_blank" rel="noopener">Открыть официальный КОД 2026</a></article>`;}
function teacher(){return `<article class="article teacher-page"><span class="section-code">ИНСТРУМЕНТЫ ПРЕПОДАВАТЕЛЯ</span><h1>Провести занятие</h1><p>Выберите тему и базу данных, затем откройте презентацию для группы.</p><div class="teacher-selectors"><label>Тема<select id="teacher-module">${year.modules.map(m=>`<option value="${m.id}" ${m.id===module.id?'selected':''}>Модуль ${m.number}. ${E(m.title)}</option>`).join('')}</select></label><label>База данных<select id="teacher-stack"><option value="mysql" ${stack==='mysql'?'selected':''}>MySQL</option><option value="postgresql" ${stack==='postgresql'?'selected':''}>PostgreSQL</option></select></label><label>Материал<select id="teacher-view"><option value="steps" ${lessonView==='steps'?'selected':''}>Пошаговый разбор</option><option value="example" ${lessonView==='example'?'selected':''}>Готовый пример</option></select></label></div><div id="teacher-actions" class="teaching-actions"></div><div id="instructor-profile"></div></article>`;}
function submission(){return `<section class="submission-guide"><h2>Куда сохранять работу</h2><ol><li>На рабочем столе создайте папку с именем, которое сообщил эксперт. В ней сохраняйте результаты всех модулей; если папка уже подготовлена, работайте в ней.</li><li>До начала работы проверьте путь в «Сохранить как». Для тренировки можно создать папку «ДЭ_2026_Фамилия» и подпапки M1–M5. На экзамене используйте установленную организатором структуру и имена.</li><li>После каждого модуля сохраните файлы, откройте их из папки сдачи и убедитесь, что это последняя версия. Ярлык на файл не заменяет сам файл.</li><li>При онлайн-сдаче будет организовано хранилище, в которое нужно загрузить все результаты. Адрес, доступ и порядок загрузки предоставит организатор. После загрузки проверьте наличие файлов и возможность их открыть.</li></ol><p>Сохранение прогресса на этом сайте не сохраняет и не отправляет ваши SQL, PDF или C#-проект.</p></section>`;}

function sourceFiles(){const own=year.practice.tasks.find(t=>t.id===module.id)?.files||[];const files=own.length?own:year.practice.tasks[0].files;return '<details class="source-files"><summary>'+ (own.length?'Исходные файлы модуля':'Исходные файлы предыдущих этапов')+' · просмотр и скачивание</summary>'+ExamResources.fileList(files)+'<p><a href="https://disk.yandex.ru/d/h3QUsGWcrr_tsQ" target="_blank" rel="noopener">Материалы преподавателя на Яндекс Диске ↗</a></p></details>';}
function lesson(){const example=section==='examples';return `<article class="article lesson"><span class="section-code">МОДУЛЬ ${module.number} · ${example?'ГОТОВЫЙ ПРОЕКТ':'СОЗДАНИЕ ПО ШАГАМ'}</span><div class="lesson-heading"><h2>${E(module.title)}</h2></div><p class="subtitle">C# Windows Forms + ${stack==='mysql'?'MySQL':'PostgreSQL'} · ООО Молочный комбинат «Полесье»</p>${example?'':assessment()+sourceFiles()}${!example&&['M2','M3','M4'].includes(module.id)?`<p class="program-shortcut"><a class="btn" href="?section=programs&guide=${module.id==='M4'?'visualstudio':stack==='postgresql'?'postgresql':module.id==='M3'?'sql':'phpmyadmin'}&stack=${stack}">Справка: ${module.id==='M4'?'всё приложение в Visual Studio':module.id==='M3'?'запрос по шагам':'создание базы'} →</a></p>`:''}${(example?EXAMPLE_LESSONS:LESSONS)[module.id][stack]}</article>`;}
function examplesPage(){return `<section class="examples-intro"><div class="examples-heading"><h1>Примеры проектов</h1></div><p>Откройте готовое решение для сравнения со своей работой. Здесь находятся запуск из архива, пояснения к коду и результаты всех пяти модулей.</p><div class="example-download-buttons"><a class="btn primary" href="downloads/polesie-mysql.zip" download>Полный проект MySQL</a><a class="btn" href="downloads/polesie-postgresql.zip" download>Полный проект PostgreSQL</a><a class="btn" href="verification.html">Проверка архивов</a></div><div class="example-selectors"><label>Что посмотреть<select id="example-module">${year.modules.map(m=>`<option value="${m.id}" ${m.id===module.id?'selected':''}>Модуль ${m.number}. ${E(m.title)}</option>`).join('')}</select></label><label>База данных<select id="example-stack"><option value="mysql" ${stack==='mysql'?'selected':''}>MySQL</option><option value="postgresql" ${stack==='postgresql'?'selected':''}>PostgreSQL</option></select></label></div></section><div class="workspace" id="lesson-workspace">${lesson()}${aside()}</div>`;}
function aside(){return `<aside class="lesson-sidebar"><h3>В этом разборе</h3><nav class="lesson-toc">${(lessonView==='steps'?LESSON_TOC:EXAMPLE_TOC)[module.id].map((t,i)=>`<a href="#${lessonView==='steps'?'lesson':'example'}-step-${i+1}">${E(t)}</a>`).join('')}</nav></aside>`;}
function goTraining(){change(()=>{section='work';mode='training';lessonView='steps';returnToTraining=false;});}
function render(){
 ExamProductTour.close();
 document.body.classList.toggle('dark',dark);
 document.title='Мой учебный проект · ДЭ 2026';
 const nav=[['learn','Обучение'],['training','Тренировка'],['mock','Пробный экзамен'],['programs','Справочник'],['examples','Примеры'],['criteria','Критерии'],['teacher','Преподавателю']];
 const current=section==='work'?mode:section;
 let body;
 if(section==='work'&&mode==='learn')body=ExamLearningRoute.render({stage:routeStage,stack,get,lesson,aside,returnToTraining});
 else if(section==='work'&&mode==='training')body=ExamTraining.render({c,year,get,set});
 else if(section==='work')body=ExamPractice.render({c,year,mode:'mock',get,set});
 else body=section==='criteria'?criteria():section==='teacher'?teacher()+ExamTraining.teacherForm():section==='examples'?examplesPage():ExamPrograms.render(stack);
 document.getElementById('app').innerHTML='<div class="shell"><header class="top"><a class="brand" href="?section=work&mode=learn"><span class="brand-emblem" aria-hidden="true">ДЭ</span><span><strong>09.02.07 · Информационные системы и программирование</strong><small>Специалист по информационным системам · 2026</small></span></a><div class="top-tools"><label>Моя СУБД <select id="app-stack"><option value="mysql" '+(stack==='mysql'?'selected':'')+'>MySQL</option><option value="postgresql" '+(stack==='postgresql'?'selected':'')+'>PostgreSQL</option></select></label><button id="theme" class="btn" aria-label="'+(dark?'Включить светлую тему':'Включить тёмную тему')+'">'+(dark?'☀':'☾')+'</button><button id="fullscreen" class="btn">На весь экран</button></div></header><nav class="site-nav" aria-label="Основные разделы">'+nav.map(([id,title],i)=>'<button class="btn '+(current===id?'active ':'')+(i===3?'nav-separator':'')+'" data-app-nav="'+id+'" '+(current===id?'aria-current="page"':'')+'>'+title+'</button>').join('')+'</nav><main id="main">'+(section==='work'?'<section class="hero study-intro"><div class="banner-mascot"><img src="mascot-scientist.png" alt="Носорог-учёный"></div><div class="banner-copy"><p class="eyebrow">ДЭ · 2026</p><h2>Подготовка к экзамену</h2><p class="lead">Изучите документы → выполните шаги → проверьте результат.</p><button class="btn banner-continue" id="banner-tour">С чего начать? Пройти тур →</button></div><a class="btn source-download" href="practice/2026/sample.zip" download>Скачать исходные материалы</a></section>':'')+(!storageAvailable?'<div class="notice" role="status">Хранилище браузера заполнено или недоступно. Новые данные сохраняются только в этой вкладке. Скачайте задание и протокол перед закрытием.</div>':'')+body+'</main><footer><span>ДЭ 2026 · Информационные системы</span><span>Самопроверка · файлы решения сохраняйте отдельно</span></footer></div>';
 document.querySelectorAll('[data-app-nav]').forEach(b=>b.onclick=()=>{if(change(()=>{const id=b.dataset.appNav;if(['learn','training','mock'].includes(id)){section='work';mode=id;lessonView='steps';if(id==='learn')module=year.modules.find(m=>m.id===(routeStage==='documents'?'M1':routeStage));}else {section=id;mode='learn';lessonView=id==='examples'?'example':'steps';}clearStepHash();}))window.scrollTo({top:0,behavior:'instant'});});
 document.getElementById('app-stack').onchange=e=>{stack=e.target.value;save();render();};
 for(const [id,action] of [['program-stack',v=>stack=v],['example-module',v=>{module=year.modules.find(m=>m.id===v);clearStepHash();}],['example-stack',v=>stack=v],['teacher-module',v=>module=year.modules.find(m=>m.id===v)],['teacher-stack',v=>stack=v],['teacher-view',v=>lessonView=v]]){const el=document.getElementById(id);if(el)el.onchange=()=>{action(el.value);save();render();};}
 ExamPrograms.mount({stack,get,set});
 document.getElementById('theme').onclick=()=>{dark=!dark;save();render();};
 document.getElementById('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});};
 if(section==='work'&&mode==='mock')ExamPractice.bind({rerender:render,download,mode:next=>change(()=>{mode=next;})});
 if(section==='work'&&mode==='training')ExamTraining.bind({rerender:render,learn:id=>{returnToTraining=true;change(()=>{routeStage=id;module=year.modules.find(m=>m.id===id);mode='learn';clearStepHash();});}});
 if(section==='teacher')ExamTraining.bindTeacher();
 ExamTeaching.mount({get,set,module,stack,lessonView,mode,section,dark,toggleTheme:()=>{dark=!dark;save();render();},html:(lessonView==='steps'?LESSONS:EXAMPLE_LESSONS)[module.id][stack],course:c,year});
 if(section==='work'||section==='examples')ExamErGuide.mount({get,set,module,stack,mode});
 ExamStudySteps.mount({get,set,module,stack,lessonView});
 if(section==='work'&&mode==='learn')ExamLearningRoute.bind({stage:routeStage,set,rerender:render,training:goTraining,change:id=>{change(()=>{routeStage=id;module=year.modules.find(m=>m.id===(id==='documents'?'M1':id));clearStepHash();});window.scrollTo({top:0,behavior:'instant'});}});
 ExamProductTour.mount();
 const bannerTour=document.getElementById('banner-tour');if(bannerTour)bannerTour.onclick=()=>ExamProductTour.start();
 if(mode==='mock')ExamPractice.tick();
}
setInterval(()=>{if(mode==='mock')ExamPractice.tick();},500);
ExamTraining.init().finally(render);
})();
