(function(root){
'use strict';
const E=root.ExamCore.escape;
const stages=[{id:'documents',module:'M1',title:'Документы',goal:'Найдите в исходных файлах сведения, которые нужно хранить в базе.'},{id:'M1',module:'M1',title:'ER-схема',goal:'Выделите сущности, поля и связи. Подготовьте читаемую ER-диаграмму.'},{id:'M2',module:'M2',title:'База данных',goal:'Перенесите свою схему в СУБД, создайте ограничения и загрузите данные.'},{id:'M3',module:'M3',title:'Расчёт',goal:'Используйте связи базы для расчёта и проверьте результат на исходных данных.'},{id:'M4',module:'M4',title:'Приложение',goal:'Подключите приложение к базе и реализуйте действия пользователя.'},{id:'M5',module:'M5',title:'Проверка и сдача',goal:'Проверьте запуск проекта и соберите документацию и файлы для сдачи.'}];
let selected='name';
function nav(stage,get){return '<aside class="route-sidebar" aria-label="Учебный маршрут"><div class="route-label">МОЙ УЧЕБНЫЙ ПРОЕКТ</div>'+stages.map((s,i)=>'<button class="route-step" data-route="'+s.id+'" '+(s.id===stage?'aria-current="step"':'')+'><span class="route-number">'+(get('route-done:'+s.id)==='true'?'✓':i+1)+'</span><span>'+s.title+'<small>'+(s.id==='documents'?'Исходные материалы':s.module)+'</small></span></button>').join('')+'<div class="route-context">Сквозной пример<br><strong>Молочный комбинат «Полесье»</strong><p>Один проект — от документов до работающей системы.</p></div></aside>';}
function documents(stack){const table=ER_GUIDE.stacks[stack].tables.find(t=>t.id==='counterparty');const f=table.fields.find(f=>f.id===selected)||table.fields[0];return '<div class="route-source-grid"><section class="route-panel"><h2>1. Изучите источник</h2><div class="route-file"><div class="route-file-title">Заказчики.json · запись 6 · фрагмент</div>'+table.fields.filter(f=>['id','name','address','phone'].includes(f.id)).map(f=>'<button class="route-field" data-source-field="'+f.id+'" aria-pressed="'+(f.id===selected)+'"><code>'+E(f.location?.match(/\[5\]\.(\w+)/)?.[1]||f.id)+'</code><span>'+E(f.value)+'</span></button>').join('')+'</div><p class="small">Выберите реквизит — справа появится его связь с моделью.</p><a class="btn" href="practice/2026/assets/M1/'+encodeURIComponent('Заказчики.json')+'" download>Скачать исходный JSON</a></section><section class="route-panel" aria-live="polite"><h2>2. Определите место в модели</h2><span class="section-code">'+E(f.title)+'</span><div class="route-mapping"><code>'+E(f.location?.match(/\[5\]\.(\w+)/)?.[1]||f.id)+'</code> → <code>counterparty.'+E(f.id)+'</code></div><div class="route-explanation">'+E(f.why)+'</div><p><strong>Таблица «Контрагенты»</strong></p><p class="small">'+E(table.why)+'</p><p class="small">'+E(f.file)+' · '+E(f.location)+'</p></section></div><details class="route-panel route-sources"><summary>Все исходные документы проекта</summary>'+ExamResources.fileList(COURSE.years[0].practice.tasks[0].files)+'</details>';}
function render({stage,stack,get,lesson,aside,returnToTraining}){const s=stages.find(s=>s.id===stage)||stages[0],index=stages.indexOf(s);return '<div class="route-layout">'+nav(s.id,get)+'<section class="route-content">'+(returnToTraining?'<div class="route-return"><span>Вы открыли объяснение из тренировки. Ваше задание и отметки сохранены.</span><button class="btn" id="return-training">Вернуться к заданию →</button></div>':'')+'<header class="route-heading"><span class="section-code">ОБУЧЕНИЕ · '+(s.id==='documents'?'НАЧАЛО ПРОЕКТА':s.module)+' · '+(stack==='mysql'?'MYSQL':'POSTGRESQL')+'</span><h1>'+s.title+'</h1><p>'+s.goal+'</p></header>'+(s.id==='documents'?documents(stack):(s.id==='M1'?'<section class="route-full-guide"><h2>От реквизита документа к полю и связи</h2><p>Постройте схему по шагам. У каждого поля — источник или объяснение принятого решения.</p><button class="btn primary" id="route-er-open">Открыть пошаговую ER-схему</button><a class="btn" href="diagrams/er.pdf" target="_blank" rel="noopener">Готовая схема в PDF</a></section>':'')+'<div class="workspace" id="lesson-workspace">'+lesson()+aside()+'</div>')+'<div class="route-check"><p>САМОПРОВЕРКА ЭТАПА</p><label><input type="checkbox" id="route-complete" '+(get('route-done:'+s.id)==='true'?'checked':'')+'>Я понимаю результат этапа и могу повторить действия самостоятельно.</label></div><div class="route-bottom"><button class="btn" data-route="'+(stages[index-1]?.id||s.id)+'" '+(index===0?'disabled':'')+'>← Назад по маршруту</button><span class="small">Этап '+(index+1)+' из '+stages.length+'</span>'+(stages[index+1]?'<button class="btn primary" data-route="'+stages[index+1].id+'">Далее: '+stages[index+1].title+' →</button>':'<button class="btn primary" id="route-go-training">Перейти к тренировке →</button>')+'</div></section></div>';}
function bind({stage,set,change,rerender,training}){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>change(b.dataset.route));document.querySelectorAll('[data-source-field]').forEach(b=>b.onclick=()=>{selected=b.dataset.sourceField;rerender();});const done=document.getElementById('route-complete');if(done)done.onchange=()=>{set('route-done:'+stage,String(done.checked));const number=document.querySelector('.route-step[aria-current=step] .route-number');if(number)number.textContent=done.checked?'✓':stages.findIndex(s=>s.id===stage)+1;};for(const id of ['return-training','route-go-training']){const b=document.getElementById(id);if(b)b.onclick=training;}const er=document.getElementById('route-er-open');if(er)er.onclick=()=>root.ExamErGuide.open();}
root.ExamLearningRoute={stages,render,bind};
})(globalThis);
