(function(root){
'use strict';
const C=root.ExamCore,E=C.escape,VERSION=1,MAX_FILE=5*1024*1024,MAX_PACKAGE=20*1024*1024;
const titles=['ER-схема','База данных','Расчёт','Приложение','Проверка и сдача'];
const outputs=['ER-диаграмма в PDF','SQL структуры и импорта данных','SQL расчёта и проверенный результат','Исходный проект приложения','Документация и результаты проверок'];
let ctx,source='variant',variantId='V01',assignment=null,active=0,state={},key='',callbacks,storageNote='';
async function assignmentStore(value){return new Promise((resolve,reject)=>{const request=indexedDB.open('demo-template-assignments',1);request.onupgradeneeded=()=>request.result.createObjectStore('packages');request.onerror=()=>reject(Error('Не удалось открыть хранилище заданий.'));request.onsuccess=()=>{const db=request.result,tx=db.transaction('packages',value?'readwrite':'readonly'),store=tx.objectStore('packages'),operation=value?store.put(value,'current'):store.get('current');let result;operation.onsuccess=()=>result=operation.result;tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(Error('Не удалось сохранить задание в браузере.'));};};});}
async function init(){try{const saved=await assignmentStore();if(saved&&/^[a-f0-9]{64}$/.test(saved.fingerprint))assignment={...validate(saved),fingerprint:saved.fingerprint};}catch{storageNote='Хранилище заданий недоступно. Загруженное задание останется только в текущей вкладке.';}}
function text(v,name,max=20000,optional=false){if(typeof v!=='string'||(!optional&&!v.trim())||v.length>max)throw Error('Проверьте поле «'+name+'».');return v.trim();}
function validate(raw){
 if(!raw||raw.format!=='de-training'||raw.version!==VERSION)throw Error('Нужен файл задания, созданный в разделе «Преподавателю».');
 const title=text(raw.title,'Название',160),description=text(raw.description,'Условие',20000),id=text(raw.id,'Код задания',100);
 if(!/^[a-zA-Z0-9_-]+$/.test(id))throw Error('Неверный код задания.');
 if(!Number.isInteger(raw.minutes)||raw.minutes<0||raw.minutes>600)throw Error('Время должно быть от 0 до 600 минут.');
 if(!Array.isArray(raw.tasks)||raw.tasks.length<1||raw.tasks.length>5)throw Error('Добавьте от одного до пяти этапов.');
 const seen=new Set(),tasks=raw.tasks.map(t=>{if(!/^M[1-5]$/.test(t.id)||seen.has(t.id))throw Error('Коды этапов должны быть уникальными: M1–M5.');seen.add(t.id);if(!Array.isArray(t.checks)||t.checks.length<1||t.checks.length>15)throw Error('Укажите от 1 до 15 критериев этапа.');return {id:t.id,title:text(t.title,'Этап',160),text:text(t.text,'Условие этапа'),output:text(t.output,'Результат',2000),checks:t.checks.map(v=>text(v,'Критерий',1000))};});
 const links=(raw.links||[]);if(!Array.isArray(links)||links.length>15)throw Error('Не более 15 ссылок.');
 const safeLinks=links.map(l=>{const url=text(l.url,'Ссылка',2000);let u;try{u=new URL(url);}catch{throw Error('Укажите полный адрес ссылки.');}if(u.protocol!=='https:'||u.username||u.password)throw Error('Материалы должны иметь HTTPS-ссылку без пароля.');return {name:text(l.name,'Название ссылки',200),url:u.href};});
 const files=raw.files||[];if(!Array.isArray(files)||files.length>12)throw Error('Не более 12 вложений.');let bytes=0;
 const safeFiles=files.map(f=>{const name=text(f.name,'Имя файла',180);if(/[\\/\x00-\x1f]/.test(name)||!/^data:application\/octet-stream;base64,[A-Za-z0-9+/]*={0,2}$/.test(f.data||''))throw Error('Повреждённое вложение.');const size=Math.floor((f.data.length-f.data.indexOf(',')-1)*3/4);if(size>MAX_FILE+2)throw Error('Вложение больше 5 МБ.');bytes+=size;return {name,data:f.data};});
 if(bytes>12*1024*1024)throw Error('Общий размер вложений превышает 12 МБ.');
 return {format:'de-training',version:VERSION,id,title,description,minutes:raw.minutes,hints:raw.hints===true,tasks,links:safeLinks,files:safeFiles};
}
function parsePackage(raw){if(raw.length>MAX_PACKAGE)throw Error('Файл задания больше 20 МБ.');let parsed;try{parsed=JSON.parse(raw);}catch{throw Error('Файл не читается: нужен JSON-пакет задания.');}return validate(parsed);}
function read(k,fallback){try{return JSON.parse(ctx.get(k))??fallback;}catch{return fallback;}}
function write(k,v){ctx.set(k,JSON.stringify(v));}
function persist(){write(key,state);}
function tasks(){return source==='teacher'?assignment?.tasks||[]:ctx.year.practice.tasks.map(t=>({...t,...currentVariant().tasks.find(v=>v.id===t.id)}));}
function currentVariant(){return ctx.year.mockVariants.find(v=>v.id===variantId)||ctx.year.mockVariants[0];}
function scopeKey(){return 'training-route-v1:'+ctx.year.year+':'+(source==='teacher'?'teacher:'+assignment.fingerprint:'variant:'+variantId);}
function load(){if(source==='teacher'&&!assignment)return;key=scopeKey();const saved=read(key,{}),minutes=source==='teacher'?assignment.minutes:150;state={checks:saved.checks&&typeof saved.checks==='object'?saved.checks:{},notes:typeof saved.notes==='string'?saved.notes:'',timer:minutes?C.restoreTimer(JSON.stringify(saved.timer||{}),minutes*60,'training'):null};active=Math.max(0,Math.min(tasks().length-1,Number(saved.active)||0));state.active=active;}
function remember(){write('training-route-preferences',{source,variantId});}
function links(){if(source==='variant'){const v=currentVariant();return '<a class="btn primary" href="'+E(v.zip)+'" download>Скачать материалы '+E(v.id)+'</a><a class="btn" href="'+E(v.document)+'" target="_blank" rel="noopener">Открыть все условия</a>';}
 return assignment.files.map((f,i)=>'<button class="btn" data-assignment-file="'+i+'">Скачать '+E(f.name)+'</button>').join('')+assignment.links.map(l=>'<a class="btn" href="'+E(l.url)+'" target="_blank" rel="noopener">'+E(l.name)+' ↗</a>').join('');}
function render(input){ctx=input;const p=read('training-route-preferences',{});source=p.source==='teacher'?'teacher':'variant';variantId=ctx.year.mockVariants.some(v=>v.id===p.variantId)?p.variantId:ctx.year.mockVariants[0].id;
 load();const chooser='<div class="training-source" role="group" aria-label="Источник задания"><button class="source-choice '+(source==='variant'?'selected':'')+'" data-training-source="variant" aria-pressed="'+(source==='variant')+'"><strong>Мой вариант</strong><span>30 комплектов · номер назначает преподаватель</span></button><button class="source-choice '+(source==='teacher'?'selected':'')+'" data-training-source="teacher" aria-pressed="'+(source==='teacher')+'"><strong>Задание преподавателя</strong><span>Свои условия, материалы и результаты</span></button></div>';
 const pick=source==='variant'?'<label class="training-picker">Мой номер <select id="training-variant">'+ctx.year.mockVariants.map(v=>'<option value="'+E(v.id)+'" '+(v.id===variantId?'selected':'')+'>'+E(v.id+' · '+v.company)+'</option>').join('')+'</select></label>':'<div class="training-import"><label class="btn">Открыть файл задания<input id="training-import" type="file" accept=".json,application/json"></label><span class="small">Файл .json выдаёт преподаватель</span><p id="training-error" role="alert"></p></div>';
 return '<section class="training-page"><div class="page-kicker">САМОСТОЯТЕЛЬНАЯ РАБОТА</div><div class="training-title"><h1>Тренировка</h1></div><p class="page-intro">Пройдите путь от документов до своего проекта. Подсказки рядом, решения выполняются в ваших программах.</p>'+chooser+pick+(source==='teacher'&&storageNote?'<p role="status" class="notice">'+E(storageNote)+'</p>':'')+(source==='teacher'&&!assignment?'<div class="empty-training"><h2>Откройте задание преподавателя</h2><p>Условия, этапы и вложения появятся здесь. Прогресс каждого задания сохраняется отдельно в этом браузере.</p><a class="btn" href="?section=teacher">Преподавателю: создать задание →</a></div>':workspace())+'</section>';
}
function workspace(){const t=tasks()[active],v=source==='variant'?currentVariant():null,minutes=v?150:assignment.minutes;const hints=v||assignment.hints;
 return '<div class="assignment-heading"><div><span class="section-code">'+E(v?v.id:'ЗАДАНИЕ ПРЕПОДАВАТЕЛЯ')+'</span><h2>'+E(v?v.company:assignment.title)+'</h2>'+(v?'':'<p class="preserve-lines">'+E(assignment.description)+'</p>')+'</div><div class="assignment-tools">'+(minutes?'<span class="training-clock" id="training-clock" role="timer"></span><span class="small">Ориентир: '+minutes+' мин</span><button class="btn" id="training-timer-toggle"></button>':'<span class="small">Без ограничения времени</span>')+'</div></div><div class="training-workspace"><nav class="training-stage-list" aria-label="Этапы тренировки">'+tasks().map((item,i)=>'<button data-training-stage="'+i+'" class="'+(i===active?'active':'')+'" '+(i===active?'aria-current="step"':'')+'><span>'+item.id+'</span>'+E(titles[Number(item.id.slice(1))-1])+'</button>').join('')+'</nav><article class="training-task"><div class="step-caption">ЭТАП '+(active+1)+' ИЗ '+tasks().length+'</div><h2>'+E(t.title)+'</h2><div class="training-condition">'+(v?ExamConditions.format(t.text,t.id,false):'<p class="preserve-lines">'+E(t.text)+'</p>')+'</div><details class="task-materials"><summary>Условие и исходные материалы</summary><div class="button-row">'+links()+'</div>'+(v?v.inputHtml:'')+'</details><section class="expected-result"><h3>Что сохранить</h3><p>'+E(t.output||outputs[Number(t.id.slice(1))-1])+'</p><span class="small">Используйте данные своего задания и результаты предыдущих этапов.</span></section>'+(hints?'<details class="training-help"><summary>Нужна подсказка</summary><p>Сначала определите, какой результат нужен на этом этапе. Сверьтесь с объяснением на учебном примере и примените принцип к своим данным.</p><button class="btn" id="training-help-link">Открыть объяснение · '+t.id+' →</button><p class="small">Учебный пример «Полесье» может отличаться от вашего задания.</p></details>':'')+'<section class="self-check"><h3>Самопроверка</h3>'+t.checks.map((check,i)=>'<label><input type="checkbox" data-training-check="'+t.id+':'+i+'" '+(state.checks[t.id+':'+i]?'checked':'')+'>'+E(check)+'</label>').join('')+'<p class="small">Это ваши отметки. Сайт не проверяет решение и не выставляет оценку.</p></section><label class="training-notes">Заметки по работе<textarea id="training-notes" maxlength="6000" placeholder="Что осталось проверить…">'+E(state.notes)+'</textarea></label><div class="training-bottom"><button class="btn" id="training-previous" '+(active===0?'disabled':'')+'>← Предыдущий этап</button><button class="btn primary" id="training-next">'+(active===tasks().length-1?'Подготовить сдачу':'Следующий этап →')+'</button></div><div id="training-submission"></div></article></div>';
}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportProgress(){return JSON.stringify({format:'de-training-progress',version:1,scope:key,taskTitle:source==='teacher'?assignment.title:currentVariant().company,exportedAt:new Date().toISOString(),state:{...state,active}},null,2);}
function bind(cb){callbacks=cb;document.querySelectorAll('[data-training-source]').forEach(b=>b.onclick=()=>{source=b.dataset.trainingSource;remember();callbacks.rerender();});const variant=document.getElementById('training-variant');if(variant)variant.onchange=()=>{variantId=variant.value;remember();callbacks.rerender();};
 const file=document.getElementById('training-import');if(file)file.onchange=async()=>{const el=document.getElementById('training-error');try{const f=file.files[0];if(!f)return;if(f.size>MAX_PACKAGE)throw Error('Файл больше 20 МБ.');const pkg=parsePackage(await f.text());const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(pkg)));pkg.fingerprint=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');assignment=pkg;try{await assignmentStore(pkg);storageNote='';}catch{storageNote='Задание открыто только в этой вкладке: браузер не смог сохранить вложения. Сохраните исходный файл задания для повторного открытия.';}callbacks.rerender();}catch(e){el.textContent=e.message;}};
 document.querySelectorAll('[data-training-stage]').forEach(b=>b.onclick=()=>{state.active=Number(b.dataset.trainingStage);persist();callbacks.rerender();});
 document.querySelectorAll('[data-training-check]').forEach(b=>b.onchange=()=>{state.checks[b.dataset.trainingCheck]=b.checked;persist();});
 document.querySelectorAll('[data-assignment-file]').forEach(b=>b.onclick=()=>{const f=assignment.files[Number(b.dataset.assignmentFile)],raw=atob(f.data.split(',')[1]);downloadBlob(new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:'application/octet-stream'}),f.name);});
 const on=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};
 const notes=document.getElementById('training-notes');if(notes)notes.oninput=()=>{state.notes=notes.value;persist();};
 on('training-help-link',()=>callbacks.learn(tasks()[active].id));
 on('training-previous',()=>{state.active=active-1;persist();callbacks.rerender();});
 on('training-next',()=>{if(active<tasks().length-1){state.active=active+1;persist();callbacks.rerender();return;}const box=document.getElementById('training-submission');box.innerHTML='<section class="submission-checklist"><h3>Подготовьте файлы для сдачи</h3><ul>'+tasks().map(t=>'<li>'+E(t.output||outputs[Number(t.id.slice(1))-1])+'</li>').join('')+'</ul><p>Откройте сохранённые файлы и передайте их способом, указанным преподавателем. Отметки на сайте не заменяют файлы работы.</p><button class="btn" id="training-export">Скачать протокол самопроверки</button><p class="small">Протокол содержит заметки и отметки, но не решение.</p></section>';document.getElementById('training-export').onclick=()=>downloadBlob(new Blob([exportProgress()],{type:'application/json'}),'Протокол-тренировки.json');box.scrollIntoView({block:'nearest'});});
 on('training-timer-toggle',()=>{state.timer=C.transition(state.timer,state.timer.status==='running'?'pause':'start');persist();tick();});tick();
}
function tick(){const clock=document.getElementById('training-clock');if(!clock||!state.timer)return;state.timer=C.checkpoint(state.timer);const v=C.timerView(state.timer);clock.textContent=(v.over?'+':'')+C.format(v.over||v.left);document.getElementById('training-timer-toggle').textContent=state.timer.status==='running'?'Пауза':state.timer.status==='paused'?'Продолжить':'Начать отсчёт';}
function teacherForm(){return '<section class="assignment-editor"><div class="page-kicker">СВОИ УСЛОВИЯ И МАТЕРИАЛЫ</div><div class="assignment-guide-heading"><h2>Создать тренировку</h2></div><p>Соберите файл задания и передайте студентам. Они откроют его в разделе «Тренировка → Задание преподавателя».</p><form id="assignment-form"><div class="editor-grid"><label>Название<input name="title" required maxlength="160" placeholder="Например: учёт заказов мастерской"></label><label>Время, минут · 0 — без таймера<input name="minutes" type="number" min="0" max="600" value="0" required></label></div><label>Общее условие<textarea name="description" required maxlength="20000" placeholder="Опишите предметную область и общую задачу"></textarea></label><label class="inline-check"><input name="hints" type="checkbox" checked>Разрешить переход к объяснениям учебного примера</label><h3>Этапы работы</h3>'+titles.map((title,i)=>'<details class="editor-stage" '+(i===0?'open':'')+'><summary>M'+(i+1)+' · '+title+'</summary><label class="inline-check"><input name="enable'+i+'" type="checkbox" checked>Включить этот этап</label><label>Задание этапа<textarea name="task'+i+'" maxlength="20000">'+['Выделите сущности, поля и связи по исходным материалам. Постройте ER-схему.','Создайте таблицы, ключи и ограничения по своей ER-схеме. Загрузите исходные данные.','Подготовьте SQL-запрос расчёта по условию и проверьте результат.','Реализуйте приложение для работы со своей базой согласно общему условию.','Подготовьте документацию, проверьте запуск и соберите результаты для сдачи.'][i]+'</textarea></label><label>Что сохранить<input name="output'+i+'" maxlength="2000" value="'+outputs[i]+'"></label><label>Самопроверка · один пункт на строку<textarea name="checks'+i+'" maxlength="15000">Результат соответствует условию задания.\nИспользованы собственные данные.\nФайлы сохранены и открываются.</textarea></label></details>').join('')+'<label>Ссылки на материалы · HTTPS, одна на строку<textarea name="links" placeholder="https://…"></textarea></label><label>Вложения · до 12 файлов, каждый до 5 МБ<input name="attachments" type="file" multiple></label><p class="small">Общий размер вложений — до 12 МБ. Для больших файлов используйте ссылки. Файлы включаются в пакет задания.</p><p id="assignment-error" role="alert"></p><button class="btn primary" type="submit">Проверить и подготовить задание</button><div id="assignment-preview" aria-live="polite"></div></form></section>';}
function bindTeacher(){const form=document.getElementById('assignment-form');if(!form)return;let prepared=null;const draftKey='teacher-assignment-draft-v1';try{const d=JSON.parse(localStorage.getItem(draftKey)||'null');if(d)for(const el of form.elements){if(!el.name||el.type==='file'||!(el.name in d))continue;if(el.type==='checkbox')el.checked=!!d[el.name];else el.value=String(d[el.name]);}}catch{}
 form.oninput=()=>{prepared=null;document.getElementById('assignment-preview').textContent='';const d={};for(const el of form.elements)if(el.name&&el.type!=='file')d[el.name]=el.type==='checkbox'?el.checked:el.value;try{localStorage.setItem(draftKey,JSON.stringify(d));}catch{document.getElementById('assignment-error').textContent='Черновик не удалось сохранить в браузере. Скачайте готовое задание перед закрытием страницы.';}};
 form.onsubmit=async e=>{e.preventDefault();const error=document.getElementById('assignment-error'),button=form.querySelector('[type=submit]');error.textContent='';button.disabled=true;try{const f=new FormData(form),files=[...form.elements.attachments.files];if(files.length>12||files.some(f=>f.size>MAX_FILE)||files.reduce((n,f)=>n+f.size,0)>12*1024*1024)throw Error('Допустимо до 12 файлов по 5 МБ; суммарно — до 12 МБ.');const embedded=[];for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));embedded.push({name:file.name,data:'data:application/octet-stream;base64,'+btoa(binary)});}
 const pkg={format:'de-training',version:1,id:crypto.randomUUID(),title:f.get('title'),description:f.get('description'),minutes:Number(f.get('minutes')),hints:f.has('hints'),tasks:titles.flatMap((title,i)=>f.has('enable'+i)?[{id:'M'+(i+1),title,text:f.get('task'+i),output:f.get('output'+i),checks:String(f.get('checks'+i)).split(/\r?\n/).map(s=>s.trim()).filter(Boolean)}]:[]),links:String(f.get('links')).split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,i)=>({name:'Материалы '+(i+1),url})),files:embedded};prepared=validate(pkg);const preview=document.getElementById('assignment-preview');preview.innerHTML='<div class="assignment-ready"><h3>'+E(prepared.title)+'</h3><p>'+prepared.tasks.length+' этапов · '+prepared.files.length+' вложений · '+(prepared.minutes?prepared.minutes+' мин':'без таймера')+'</p><p class="preserve-lines">'+E(prepared.description)+'</p><ol>'+prepared.tasks.map(t=>'<li>'+E(t.title)+' — '+E(t.output)+'</li>').join('')+'</ol><button class="btn primary" type="button" id="assignment-download">Скачать файл задания</button></div>';document.getElementById('assignment-download').onclick=()=>{if(prepared)downloadBlob(new Blob([JSON.stringify(prepared,null,2)],{type:'application/json'}),'Задание-'+prepared.id.slice(0,8)+'.json');};preview.scrollIntoView({block:'nearest'});
 }catch(e){error.textContent=e.message;}finally{button.disabled=false;}};
}
if(typeof document!=='undefined'){setInterval(()=>{if(document.getElementById('training-clock')){tick();if(state.timer?.status==='running')persist();}},1000);addEventListener('pagehide',()=>{if(key&&state.timer)persist();});}
root.ExamTraining={init,render,bind,tick,teacherForm,bindTeacher,validate,parsePackage,scopeKey,isRunning:()=>state.timer?.status==='running'};
})(globalThis);
