import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import '../src/core.js';import '../src/practice.js';
const C=ExamCore,P=ExamPractice,root=path.resolve(import.meta.dirname,'..');
const courses=['is','web','programmer'].map(s=>JSON.parse(fs.readFileSync(path.join(root,'content',s+'.json'),'utf8')));
test('six full published samples have matching tasks, time and real files',()=>{
 for(const c of courses)for(const y of c.years){const p=y.practice;assert.equal(p.kind,'published-sample');assert.equal(p.ready,true);assert.equal(p.tasks.length,y.modules.length);assert.equal(p.tasks.reduce((s,t)=>s+t.seconds,0),y.totalSeconds);assert.ok(fs.existsSync(path.join(root,'dist',c.slug,p.zip)));for(const t of p.tasks){assert.ok(t.text.length>100);assert.ok(t.checks.length>=3);assert.ok(t.hints.length>=3);assert.ok(fs.existsSync(path.join(root,'dist',c.slug,t.zip)));for(const f of t.files)assert.ok(fs.existsSync(path.join(root,'dist',c.slug,f.url)),f.url);}}
});
test('sample gate rejects missing task while complete course gate stays separate',()=>{const c=structuredClone(courses[0]);c.years[0].practice.tasks.pop();assert.throws(()=>C.validateCourse(c),/Неполный образец/);assert.throws(()=>C.validateCourse(courses[0],true),/полный комплект/);});
test('scope isolation across mode, year, task and individual exercise',()=>{const c=courses[0],y=c.years[0];const keys=[P.stateKey(c,y,'mock','sample'),P.stateKey(c,y,'training','M1:sample'),P.stateKey(c,y,'training','V01:exercise'),P.stateKey(c,y,'training','V02:exercise'),P.stateKey(c,c.years[1],'mock','sample')];assert.equal(new Set(keys).size,5);});
test('mock timer survives reload, and switching task does not start a new clock',()=>{const s=P.restore(null,12600,'mock');s.timer=C.transition(s.timer,'start',1000);s.selected='M5';const r=P.restore(JSON.stringify(s),12600,'mock');assert.equal(r.selected,'M5');assert.equal(C.elapsed(r.timer,61000),60000);assert.throws(()=>C.transition(r.timer,'pause',61000),/пауза/);});
test('corrupt state restores safely and notes/checks remain bounded',()=>{assert.equal(P.restore('{',60,'training').timer.status,'idle');const r=P.restore(JSON.stringify({notes:'x'.repeat(10000),checks:[],done:[null,'M1']}),60,'training');assert.equal(r.notes.length,6000);assert.deepEqual(r.checks,{});assert.deepEqual(r.done,['M1']);});
test('2027 IS includes operations, notes API and original documentation template',()=>{const y=courses[0].years[1];assert.match(y.practice.tasks[2].text,/технологических/);assert.match(y.practice.tasks[4].supplements[0].text,/title_user/);assert.ok(y.practice.tasks[5].files.some(f=>f.name.endsWith('.docx')));assert.equal(y.practice.tasks[4].seconds,3600);});
test('training and mock output differ: hints only in training and preparation gate in mock',()=>{const c=courses[0],year=c.years[1],get=()=>null,set=()=>{};const training=P.render({c,year,mode:'training',get,set});assert.match(training,/Если застряли/);assert.match(training,/Самопроверка/);const mock=P.render({c,year,mode:'mock',get,set});assert.match(mock,/Перед началом/);assert.match(mock,/data-prepared/);assert.doesNotMatch(mock,/practice-hint|id="practice-pause"/);});
